language: ruby
before_install:
  - 'sudo hostname $(hostname -s).x'
  - 'PATH=/usr/lib/rabbitmq/bin:$PATH ./spec/integration/bin/clusterctl start'
rvm:
  - jruby
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
